version: '3'
services:
  nginx:
    image: nginx:syamashi
    build:
      context: ./requirements/nginx # Dockerfileのあるディレクトリを指定
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - inception-network
  wordpress:
    image: wordpress:syamashi
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - inception-network
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:syamashi
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-network
networks:
  inception-network:

volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind