version: '3.5'
services:
  nginx:
    image: nginx:syamashi
    build:
      context: ./nginx # Dockerfileのあるディレクトリを指定
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - /home/user42/Desktop/data/wordpress:/home/user/data/wp_data
    env_file:
      - .env
    networks:
      - inception-network
  wordpress:
    image: wordpress:syamashi
    build:
      context: ./wordpress
    container_name: wordpress
    restart: always
    expose:
      - 9000
    volumes:
      - /home/user42/Desktop/data/wordpress:/home/user/data/wp_data
    env_file:
      - .env
    networks:
      - inception-network
  db:
    image: mariadb:syamashi
    build:
      context: ./mariadb
    container_name: db
    restart: always
    volumes:
      - /home/user42/Desktop/data/mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-network
networks:
  inception-network:
    driver: bridge