version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - web:/var/www/html
    networks:
      - public
    ports:
      - "443:443"
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - web:/var/www/html
    networks:
      - public
      - private
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_FILE_ONINSTALL: ${WP_FILE_ONINSTALL}
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - private
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "8080:8080"
    networks:
      - private

networks:
  public:
  private:

volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind
